title: Mac Frontend Developer Setup
description: Complete modular Mac development environment setup scripts tailored for frontend developers
url: https://allanasp.github.io/Setup-Developer-Mac

# GitHub Pages settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  scripts:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - index.md
  - tools-guide.md
  - script-guide.md
  - post-installation.md
  - setup-checker.md

# Social media
github_username: allanasp

# SEO
twitter:
  username: allanasp
  card: summary_large_image

# Google Analytics (optional)
# google_analytics: G-XXXXXXXXXX

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - setup.sh
  - check-setup.sh
  - "*.sh"